### ISSUE TITLE
Wrong date string serialization in jsonschema 

### ISSUE THREAD

**Issue by gallejesus** [akurdyukov/tap-clickhouse#10] opened 2024-02-08 09:31 UTC
Hello,

We are finding an issue when dealing with Date columns due to String serialization.

In Meltano SDK, a Date it being serialized as f"{elem.isoformat()}T00:00:00+00:00" (https://github.com/meltano/sdk/blob/b02d698c15c1fff8667e18e5301c65a0fd0247b5/singer_sdk/helpers/_typing.py#L477-L478) which will always fail afterwards jsonschema validation, as the serialized string does not match jsconschema Date format (https://json-schema.org/understanding-json-schema/reference/string#dates-and-times).

Several taps have already implemented a workaround:

- Snowflake: https://github.com/MeltanoLabs/tap-snowflake/blob/7924641d939cdf486f9c048f224a1ee6ddc5ee03/tap_snowflake/client.py#L27
- Postgres: https://github.com/MeltanoLabs/tap-postgres/blob/8528854a092f2ba9cc574cedb31763f404e88dbf/tap_postgres/client.py#L34C5-L34C20

cc: @Plozano94

**Comment by pulsar256** [comment] 2024-07-26 20:28
here is another workaround which can be applied in the tap configuration:

```yaml
(...)
      stream_maps:
        my_stream:
          my_date: _['my_date'][0:10]
```

Is this a reported issue in the SDK? I skimmed through the open issues and was not able to spot it right away.

**Comment by pulsar256** [comment] 2024-08-05 07:47
> Is this a reported issue in the SDK? I skimmed through the open issues and was not able to spot it right away.

https://github.com/meltano/sdk/issues/1831

**Comment by pulsar256** [comment] 2024-08-08 06:42
fixed upstream in the SDK https://github.com/meltano/sdk/pull/2580 in and released with 0.39.1 https://github.com/meltano/sdk/releases/tag/v0.39.1

**Comment by akurdyukov** [comment] 2024-08-09 09:21
Ok, I'll try to update SDK in this project this weekend.

**Closed** 2024-08-17 21:16 UTC

**Comment by akurdyukov** [comment] 2024-08-17 21:19
Please check and reopen if the problem isn't fixed
